// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Mock DB implementation — used when Supabase is unreachable
class MockSupabaseQueryBuilder {
  private tableName: string;
  private filters: Array<(item: any) => boolean> = [];
  private isInsert = false;
  private isUpdate = false;
  private isDelete = false;
  private insertValues: any = null;
  private updateValues: any = null;
  private orderCol: string | null = null;
  private orderAscending = true;

  constructor(tableName: string) {
    this.tableName = tableName;
  }

  private getItems(): any[] {
    if (typeof window === "undefined") return [];
    const data = localStorage.getItem(`taj_mock_db_${this.tableName}`);
    if (data) {
      try {
        return JSON.parse(data);
      } catch {
        return [];
      }
    }
    // Default seed data for medicines
    if (this.tableName === "medicines") {
      const items = [
        { id: "med_1", name: "Paracetamol 650mg", price: 15.00, stock: 100, created_at: new Date().toISOString() },
        { id: "med_2", name: "Amoxicillin 500mg", price: 45.00, stock: 50, created_at: new Date().toISOString() },
        { id: "med_3", name: "Ibuprofen 400mg", price: 20.00, stock: 80, created_at: new Date().toISOString() },
        { id: "med_4", name: "Cetirizine 10mg", price: 12.00, stock: 120, created_at: new Date().toISOString() },
      ];
      localStorage.setItem(`taj_mock_db_${this.tableName}`, JSON.stringify(items));
      return items;
    }
    return [];
  }

  private saveItems(items: any[]) {
    if (typeof window === "undefined") return;
    localStorage.setItem(`taj_mock_db_${this.tableName}`, JSON.stringify(items));
    window.dispatchEvent(new CustomEvent("taj_mock_db_update", { detail: { table: this.tableName } }));
  }

  select(_columns: string = "*") {
    return this;
  }

  insert(values: any) {
    this.isInsert = true;
    this.insertValues = values;
    return this;
  }

  update(values: any) {
    this.isUpdate = true;
    this.updateValues = values;
    return this;
  }

  delete() {
    this.isDelete = true;
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push((item) => item[column] === value);
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push((item) => item[column] !== value);
    return this;
  }

  order(column: string, options?: { ascending: boolean }) {
    this.orderCol = column;
    this.orderAscending = options?.ascending ?? true;
    return this;
  }

  limit(_count: number) {
    return this;
  }

  private execute() {
    let items = this.getItems();
    let result: any = null;

    if (this.isInsert) {
      const records = Array.isArray(this.insertValues) ? this.insertValues : [this.insertValues];
      const newRecords = records.map(r => ({
        id: r.id || `mock_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        ...r
      }));
      this.saveItems([...newRecords, ...items]);
      result = Array.isArray(this.insertValues) ? newRecords : newRecords[0];
    } else if (this.isUpdate) {
      let singleUpdated: any = null;
      items = items.map(item => {
        const matches = this.filters.every(f => f(item));
        if (matches) {
          const updated = { ...item, ...this.updateValues, updated_at: new Date().toISOString() };
          singleUpdated = updated;
          return updated;
        }
        return item;
      });
      this.saveItems(items);
      result = singleUpdated;
    } else if (this.isDelete) {
      const remaining = items.filter(item => !this.filters.every(f => f(item)));
      this.saveItems(remaining);
      result = null;
    } else {
      let filtered = items;
      if (this.filters.length > 0) {
        filtered = items.filter(item => this.filters.every(f => f(item)));
      }
      if (this.orderCol) {
        const col = this.orderCol;
        const asc = this.orderAscending;
        filtered.sort((a, b) => {
          const valA = a[col];
          const valB = b[col];
          if (valA < valB) return asc ? -1 : 1;
          if (valA > valB) return asc ? 1 : -1;
          return 0;
        });
      }
      result = filtered;
    }

    return { data: result, error: null };
  }

  single() {
    const { data, error } = this.execute();
    const item = Array.isArray(data) ? (data[0] || null) : data;
    return Promise.resolve({ data: item, error });
  }

  maybeSingle() {
    return this.single();
  }

  then(resolve: any, reject?: any) {
    const { data, error } = this.execute();
    return Promise.resolve({ data, error }).then(resolve, reject);
  }
}

function createMockSupabaseClient() {
  const channelHandlers = new Map<any, () => void>();

  return {
    from: (tableName: string) => {
      return new MockSupabaseQueryBuilder(tableName);
    },
    channel: (_name: string) => {
      const channelObj = {
        on: function(_event: string, _filter: any, callback: any) {
          if (typeof window !== "undefined") {
            const handler = () => callback({});
            window.addEventListener("taj_mock_db_update", handler);
            channelHandlers.set(channelObj, handler);
          }
          return channelObj;
        },
        subscribe: function() {
          return channelObj;
        }
      };
      return channelObj;
    },
    removeChannel: (channel: any) => {
      if (channel && typeof window !== "undefined") {
        const handler = channelHandlers.get(channel);
        if (handler) {
          window.removeEventListener("taj_mock_db_update", handler);
          channelHandlers.delete(channel);
        }
      }
    }
  };
}

function wrapClientWithFallback(realClient: any) {
  const isMockActive = () =>
    typeof window !== "undefined" && localStorage.getItem("taj_use_mock_db") === "true";

  let mockClientInstance: ReturnType<typeof createMockSupabaseClient> | null = null;

  const getOrCreateMockClient = () => {
    if (!mockClientInstance) {
      mockClientInstance = createMockSupabaseClient() as any;
    }
    return mockClientInstance;
  };

  const activateMock = () => {
    if (typeof window !== "undefined") {
      localStorage.setItem("taj_use_mock_db", "true");
      console.warn("[Supabase] Network unreachable. Switched to localStorage mock DB.");
    }
  };

  /**
   * Creates a fully chainable proxy that:
   * 1. Records every chain call (select, eq, order, …)
   * 2. Replays them on the real Supabase builder
   * 3. If a network error occurs on the final await, activates mock mode
   *    and replays all recorded calls on MockSupabaseQueryBuilder instead.
   */
  const createBuilderProxy = (tableName: string): any => {
    let realBuilder: any = realClient.from(tableName);
    // Recorded ops for mock replay
    const ops: Array<{ m: string; a: any[] }> = [];

    const replayMock = (): any => {
      let b: any = new MockSupabaseQueryBuilder(tableName);
      for (const { m, a } of ops) {
        if (typeof b[m] === "function") {
          const ret = b[m](...a);
          if (ret !== undefined) b = ret;
        }
      }
      return b;
    };

    const isNetworkError = (res: any) =>
      res?.error?.message && (
        res.error.message.includes("fetch failed") ||
        res.error.message.includes("ENOTFOUND") ||
        res.error.message.includes("Failed to fetch") ||
        res.error.message.includes("NetworkError")
      );

    const withFallback = (p: Promise<any>): Promise<any> =>
      Promise.resolve(p).then(
        (res: any) => {
          if (isNetworkError(res)) {
            activateMock();
            return replayMock();
          }
          return res;
        },
        (_err: any) => {
          activateMock();
          return replayMock();
        }
      );

    const proxy: any = new Proxy({}, {
      get(_t, prop: string) {
        // Awaited directly without calling .single() first
        if (prop === "then") {
          return (res: any, rej?: any) => {
            if (isMockActive()) {
              return Promise.resolve(replayMock()).then(res, rej);
            }
            return withFallback(Promise.resolve(realBuilder)).then(res, rej);
          };
        }
        // Terminal call: .single() or .maybeSingle()
        if (prop === "single" || prop === "maybeSingle") {
          return () => {
            ops.push({ m: prop, a: [] });
            if (isMockActive()) {
              const mb = replayMock();
              return mb[prop] ? mb[prop]() : mb;
            }
            const term = realBuilder && typeof realBuilder[prop] === "function"
              ? realBuilder[prop]()
              : Promise.resolve({ data: null, error: null });
            return withFallback(term);
          };
        }
        // All chainable methods: select, insert, update, delete, eq, neq, order, limit, etc.
        return (...args: any[]) => {
          ops.push({ m: prop, a: args });
          if (isMockActive()) {
            // nothing — replayMock() will replay all ops when resolved
          } else if (realBuilder && typeof realBuilder[prop] === "function") {
            realBuilder = realBuilder[prop](...args);
          }
          return proxy;
        };
      }
    });

    return proxy;
  };

  return {
    ...realClient,
    from: (tableName: string) => {
      if (isMockActive()) {
        // Directly return mock builder — no proxy needed
        return new MockSupabaseQueryBuilder(tableName);
      }
      try {
        return createBuilderProxy(tableName);
      } catch {
        activateMock();
        return new MockSupabaseQueryBuilder(tableName);
      }
    },
    channel: (name: string) => {
      if (isMockActive()) {
        return getOrCreateMockClient().channel(name);
      }
      try {
        return realClient.channel(name);
      } catch {
        return getOrCreateMockClient().channel(name);
      }
    },
    removeChannel: (channel: any) => {
      try {
        realClient.removeChannel(channel);
      } catch {}
      if (mockClientInstance) {
        try {
          mockClientInstance.removeChannel(channel);
        } catch {}
      }
    }
  } as any;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return wrapClientWithFallback(realClient);
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
